### ISSUE TITLE
Bug on page break insertion

### ISSUE THREAD

**Issue by lebonsavane** [levonet/grapesjs-plugin-page-break#1]
Hi ! 
I have a problem with the plugin page break. When i insert a page-break he inserts nothing and he says that he didn't found a type page-break. Watch below:
![image](https://user-images.githubusercontent.com/39559339/93783384-eab8e300-fc2b-11ea-8290-bceecb33acb5.png)

**Comment by lebonsavane** [comment]
@levonet ??? some solution to my issue ?

**Comment by levonet** [comment]
@lebonsavane At first I thought that the plugins API had changed in newer versions of grapesjs.
I checked this, the plugin works with the latest version.

How can this problem be reproduced?

**Comment by lebonsavane** [comment]
Hello, 
@levonet it appaears when you just insert a page break for me, i use the latest version of grapesJs i think. 
Thank you for helping

**Comment by levonet** [comment]
Please show how you define the script in the `<head>` section.

**Comment by lebonsavane** [comment]
No problem, 
    <script src="grapesjs-plugin-page-break\dist/grapesjs-page-break.min.js"></script>

**Comment by levonet** [comment]
Try this if the bundle is built from local files:
```html
<script src="grapesjs-plugin-page-break/dist/grapesjs-page-break.min.js"></script>
```
Or try downloading the script from CDN:
```html
<script src="https://unpkg.com/grapesjs-page-break@0.2.0/dist/grapesjs-page-break.min.js"></script>
```

**Comment by lebonsavane** [comment]
i'll try thank you

**Comment by davidecavestro** [comment]
@lebonsavane same issue here. Did you solve it? 
I'm loading the plugin from `<script src="https://unpkg.com/grapesjs-page-break@0.2.0/dist/grapesjs-page-break.min.js"></script>`.
