### ISSUE TITLE
Page break automatic

### ISSUE THREAD

**Issue by lebonsavane** [levonet/grapesjs-plugin-page-break#8]
Hello 
Is-it possible to put automatic page break in the body, for example every 500px you put a page Break ? 
Sincerly 
thanks @levonet

**Comment by levonet** [comment]
Page break is a very simple component. It inserts tag:
```html
<div style="height: 0; width: 100%; margin: 0; page-break-before: always"></div>
```
You shouldn't expect anything more.
If you have an idea, you can create a new component.

**Comment by lebonsavane** [comment]
I thought there is a man to pu an automatic pageBreak every 842px to do like a text editor and to have multiple pages. That was my idea but thanks for helping.
